---
version: 2
updates:
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /
    open-pull-requests-limit: 100
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    assignees: [hougesen]
    directory: /cli
    open-pull-requests-limit: 100
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    assignees: [hougesen]
    directory: /
    open-pull-requests-limit: 100
    exclude-paths: [.github/workflows/release.yml]
    schedule:
      interval: weekly
